Algoritmo "ex3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/10/2022
Var
// Seção de Declarações das variáveis 
   n1, n2, n3, m: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   leia (n1, n2, n3)
   m <- (n1+n2+n3)/3
   escreva (m)

Fimalgoritmo