Algoritmo "ex4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/10/2022
Var
// Seção de Declarações das variáveis 
   x, y: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 5
   y <- 3

   escreval ("Soma = ", x + y)

Fimalgoritmo